prefix=${prefix:-$1}
sysconfdir="${prefix}/etc"
localstatedir="${prefix}/var"

configureBaseArgs=(
  --enable-shared
  --disable-static
  --prefix=${prefix}
  --sysconfdir=${sysconfdir}
  --localstatedir=${localstatedir}
)
mesonBaseArgs=(
  --buildtype=release
  --strip
  --prefix=${prefix}
  --sysconfdir=${sysconfdir}
  --localstatedir=${localstatedir}
)
cmakeBaseArgs=(
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_SYSTEM_NAME=Android
  -DCMAKE_TOOLCHAIN_FILE="${ndkDir:-$2}/build/cmake/android.toolchain.cmake"
  -DANDROID_PLATFORM=android-${api}
  -DCMAKE_C_COMPILER_LAUNCHER=ccache
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
  -DCMAKE_INSTALL_PREFIX=${prefix}
  -DCMAKE_INSTALL_SYSCONFDIR=${sysconfdir}
  -DCMAKE_INSTALL_LOCALSTATEDIR=${localstatedir}
  -DCMAKE_PREFIX_PATH=${prefix}
)

#
#   -DCMAKE_C_COMPILER_LAUNCHER=ccache
#-DCMAKE_CXX_COMPILER_LAUNCHER=ccache